"""Generate the explicit RPC allowlist from the shared command signatures."""
from pathlib import Path
import re
root = Path(__file__).resolve().parents[1]
lines = ['// Generated by scripts/generate-web-dispatch.py. Only listed commands are callable.',
         'use serde_json::Value;', 'use crate::{commands, video_upscale, video_posters, platform::{State, Channel}};',
         'use super::{WebState, rpc::{argument, channel}};',
         'pub async fn dispatch(state: &WebState, command: &str, args: &Value) -> Result<Value, String> {',
         'match command {']
count = 0
for module in ['commands','video_upscale','video_posters']:
    text = (root / 'src-tauri/src' / f'{module}.rs').read_text(encoding='utf-8')
    pattern = r'#\[cfg_attr\(feature = "desktop", tauri::command[^\n]*\)\]\s*(?:#\[[^\n]*\]\s*)*pub (async )?fn (\w+)\((.*?)\)\s*->'
    for match in re.finditer(pattern, text, re.S):
        params = re.findall(r'(\w+)\s*:\s*([^\n]+?)(?=,\s*\n|$)', match[3])
        if '\n' not in match[3] and match[3].strip():
            # Single-line command signatures contain State<'_, T> with a comma.
            params = re.findall(r'(\w+)\s*:\s*(.*?)(?=,\s*\w+\s*:|$)', match[3])
        args = []
        for name, kind in params:
            if name == 'state': args.append('State(&state.core)')
            elif name == 'app': args.append('state.handle.clone()')
            elif 'Channel' in kind: args.append('Channel::new(channel(state, args))')
            else:
                parts = name.split('_')
                key = parts[0] + ''.join(p[:1].upper()+p[1:] for p in parts[1:])
                args.append(f'argument(args, "{key}")?')
        call = f'{module}::{match[2]}({", ".join(args)})' + ('.await' if match[1] else '')
        fallible = '' if match[2] == 'get_runtime_info' else '?'
        lines.append(f'"{match[2]}" => serde_json::to_value({call}{fallible}).map_err(|e| e.to_string()),')
        count += 1
lines += ['_ => Err(format!("Unknown command: {command}")),', '}', '}']
(root / 'src-tauri/src/web/dispatch.rs').write_text('\n'.join(lines)+'\n', encoding='utf-8')
print(f'Generated {count} commands')
