// Generated by scripts/generate-web-dispatch.py. Only listed commands are callable.
use super::{
    rpc::{argument, channel},
    WebState,
};
use crate::{
    commands,
    platform::{Channel, State},
    video_posters, video_upscale,
};
use serde_json::Value;
pub async fn dispatch(state: &WebState, command: &str, args: &Value) -> Result<Value, String> {
    match command {
        "export_app_backup" => serde_json::to_value(
            commands::export_app_backup(
                argument(args, "destinationPath")?,
                argument(args, "frontendSettings")?,
                State(&state.core),
            )
            .await?,
        )
        .map_err(|e| e.to_string()),
        "stage_app_backup_restore" => serde_json::to_value(
            commands::stage_app_backup_restore(argument(args, "bundlePath")?, State(&state.core))
                .await?,
        )
        .map_err(|e| e.to_string()),
        "take_restored_frontend_settings" => serde_json::to_value(
            commands::take_restored_frontend_settings(State(&state.core))?,
        )
        .map_err(|e| e.to_string()),
        "get_app_lock_status" => {
            serde_json::to_value(commands::get_app_lock_status(State(&state.core))?)
                .map_err(|e| e.to_string())
        }
        "verify_app_lock_password" => serde_json::to_value(
            commands::verify_app_lock_password(argument(args, "password")?, State(&state.core))
                .await?,
        )
        .map_err(|e| e.to_string()),
        "set_app_lock_password" => serde_json::to_value(
            commands::set_app_lock_password(argument(args, "input")?, State(&state.core)).await?,
        )
        .map_err(|e| e.to_string()),
        "disable_app_lock" => serde_json::to_value(
            commands::disable_app_lock(argument(args, "password")?, State(&state.core)).await?,
        )
        .map_err(|e| e.to_string()),
        "load_workspace" => serde_json::to_value(commands::load_workspace(
            argument(args, "canvasId")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "update_canvas_selection" => serde_json::to_value(commands::update_canvas_selection(
            argument(args, "canvasId")?,
            argument(args, "nodeIds")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "inspect_workspace" => serde_json::to_value(commands::inspect_workspace(
            argument(args, "canvasId")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "list_projects" => serde_json::to_value(commands::list_projects(State(&state.core))?)
            .map_err(|e| e.to_string()),
        "list_project_summaries" => {
            serde_json::to_value(commands::list_project_summaries(State(&state.core))?)
                .map_err(|e| e.to_string())
        }
        "create_project" => serde_json::to_value(commands::create_project(
            argument(args, "input")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "group_nodes_into_folder" => serde_json::to_value(commands::group_nodes_into_folder(
            argument(args, "input")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "create_empty_folder" => serde_json::to_value(commands::create_empty_folder(
            argument(args, "input")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "group_related_nodes_into_folder" => {
            serde_json::to_value(commands::group_related_nodes_into_folder(
                argument(args, "input")?,
                State(&state.core),
            )?)
            .map_err(|e| e.to_string())
        }
        "undo_folder_grouping" => serde_json::to_value(commands::undo_folder_grouping(
            argument(args, "input")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "merge_folders" => serde_json::to_value(commands::merge_folders(
            argument(args, "input")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "undo_folder_merge" => serde_json::to_value(commands::undo_folder_merge(
            argument(args, "input")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "cancel_folder" => serde_json::to_value(commands::cancel_folder(
            argument(args, "input")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "undo_cancel_folder" => serde_json::to_value(commands::undo_cancel_folder(
            argument(args, "input")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "delete_folder_tree" => serde_json::to_value(commands::delete_folder_tree(
            argument(args, "input")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "undo_delete_folder_tree" => serde_json::to_value(commands::undo_delete_folder_tree(
            argument(args, "input")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "update_project" => serde_json::to_value(commands::update_project(
            argument(args, "input")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "set_project_private" => serde_json::to_value(commands::set_project_private(
            argument(args, "input")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "set_project_preview_image" => serde_json::to_value(commands::set_project_preview_image(
            argument(args, "input")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "delete_project" => serde_json::to_value(commands::delete_project(
            argument(args, "id")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "create_node" => serde_json::to_value(commands::create_node(
            argument(args, "input")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "import_media" => serde_json::to_value(
            commands::import_media(
                argument(args, "path")?,
                argument(args, "canvasId")?,
                argument(args, "x")?,
                argument(args, "y")?,
                State(&state.core),
            )
            .await?,
        )
        .map_err(|e| e.to_string()),
        "export_media_asset" => serde_json::to_value(
            commands::export_media_asset(
                argument(args, "sourcePath")?,
                argument(args, "destinationPath")?,
                State(&state.core),
            )
            .await?,
        )
        .map_err(|e| e.to_string()),
        "export_generated_video" => serde_json::to_value(
            commands::export_generated_video(
                argument(args, "sourcePath")?,
                argument(args, "destinationPath")?,
            )
            .await?,
        )
        .map_err(|e| e.to_string()),
        "export_generated_image" => serde_json::to_value(
            commands::export_generated_image(
                argument(args, "sourcePath")?,
                argument(args, "destinationPath")?,
            )
            .await?,
        )
        .map_err(|e| e.to_string()),
        "cleanup_resize_images" => {
            serde_json::to_value(commands::cleanup_resize_images(State(&state.core)).await?)
                .map_err(|e| e.to_string())
        }
        "resize_image" => serde_json::to_value(
            commands::resize_image(
                argument(args, "sourceNodeId")?,
                argument(args, "sourcePath")?,
                argument(args, "originalName")?,
                argument(args, "canvasId")?,
                argument(args, "maxEdge")?,
                argument(args, "x")?,
                argument(args, "y")?,
                argument(args, "width")?,
                argument(args, "height")?,
                State(&state.core),
            )
            .await?,
        )
        .map_err(|e| e.to_string()),
        "update_node" => serde_json::to_value(commands::update_node(
            argument(args, "input")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "delete_node" => serde_json::to_value(commands::delete_node(
            argument(args, "id")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "delete_video_files" => {
            serde_json::to_value(commands::delete_video_files(argument(args, "paths")?).await?)
                .map_err(|e| e.to_string())
        }
        "delete_image_files" => {
            serde_json::to_value(commands::delete_image_files(argument(args, "paths")?).await?)
                .map_err(|e| e.to_string())
        }
        "delete_nodes_undoable" => serde_json::to_value(commands::delete_nodes_undoable(
            argument(args, "input")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "restore_deleted_nodes" => serde_json::to_value(commands::restore_deleted_nodes(
            argument(args, "batch")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "replace_node_and_delete_undoable" => {
            serde_json::to_value(commands::replace_node_and_delete_undoable(
                argument(args, "input")?,
                State(&state.core),
            )?)
            .map_err(|e| e.to_string())
        }
        "restore_node_replacement" => serde_json::to_value(commands::restore_node_replacement(
            argument(args, "input")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "create_edge" => serde_json::to_value(commands::create_edge(
            argument(args, "input")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "delete_edge" => serde_json::to_value(commands::delete_edge(
            argument(args, "id")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "list_workflow_modules" => serde_json::to_value(commands::list_workflow_modules(
            state.handle.clone(),
            argument(args, "includeDeleted")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "save_workflow_module" => serde_json::to_value(commands::save_workflow_module(
            argument(args, "input")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "validate_workflow_module_source" => {
            serde_json::to_value(commands::validate_workflow_module_source(
                argument(args, "sourceWorkflowPath")?,
                argument(args, "AdapterKind")?,
                argument(args, "variant")?,
                argument(args, "bindings")?,
                argument(args, "adapter")?,
                argument(args, "uiSchema")?,
            )?)
            .map_err(|e| e.to_string())
        }
        "trash_workflow_module" => serde_json::to_value(commands::trash_workflow_module(
            argument(args, "id")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "restore_workflow_module" => serde_json::to_value(commands::restore_workflow_module(
            argument(args, "id")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "purge_workflow_module" => serde_json::to_value(commands::purge_workflow_module(
            argument(args, "id")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "restore_workflow_module_backup" => serde_json::to_value(
            commands::restore_workflow_module_backup(argument(args, "id")?, State(&state.core))?,
        )
        .map_err(|e| e.to_string()),
        "export_workflow_module" => serde_json::to_value(commands::export_workflow_module(
            argument(args, "id")?,
            State(&state.core),
        )?)
        .map_err(|e| e.to_string()),
        "import_workflow_module_bundle" => {
            serde_json::to_value(commands::import_workflow_module_bundle(
                argument(args, "bundlePath")?,
                State(&state.core),
            )?)
            .map_err(|e| e.to_string())
        }
        "restore_workflow_module_bundle" => {
            serde_json::to_value(commands::restore_workflow_module_bundle(
                argument(args, "id")?,
                argument(args, "bundlePath")?,
                State(&state.core),
            )?)
            .map_err(|e| e.to_string())
        }
        "get_comfyui_krea2_diffusion_models" => serde_json::to_value(
            commands::get_comfyui_krea2_diffusion_models(
                argument(args, "serverUrl")?,
                argument(args, "workflowModuleId")?,
                State(&state.core),
            )
            .await?,
        )
        .map_err(|e| e.to_string()),
        "get_comfyui_h3_loras" => serde_json::to_value(
            commands::get_comfyui_h3_loras(argument(args, "serverUrl")?).await?,
        )
        .map_err(|e| e.to_string()),
        "get_comfyui_krea2_loras" => serde_json::to_value(
            commands::get_comfyui_krea2_loras(argument(args, "serverUrl")?).await?,
        )
        .map_err(|e| e.to_string()),
        "get_comfyui_h3_diffusion_models" => serde_json::to_value(
            commands::get_comfyui_h3_diffusion_models(
                argument(args, "serverUrl")?,
                argument(args, "workflowModuleId")?,
                State(&state.core),
            )
            .await?,
        )
        .map_err(|e| e.to_string()),
        "submit_comfyui_image_workflow" => serde_json::to_value(
            commands::submit_comfyui_image_workflow(argument(args, "input")?, State(&state.core))
                .await?,
        )
        .map_err(|e| e.to_string()),
        "submit_comfyui_image_upscale" => serde_json::to_value(
            commands::submit_comfyui_image_upscale(argument(args, "input")?, State(&state.core))
                .await?,
        )
        .map_err(|e| e.to_string()),
        "submit_comfyui_workflow" => serde_json::to_value(
            commands::submit_comfyui_workflow(
                argument(args, "input")?,
                State(&state.core),
                Channel::new(channel(state, args)),
            )
            .await?,
        )
        .map_err(|e| e.to_string()),
        "get_comfyui_queue_summary" => serde_json::to_value(
            commands::get_comfyui_queue_summary(argument(args, "serverUrl")?).await?,
        )
        .map_err(|e| e.to_string()),
        "get_comfyui_client_task_statuses" => serde_json::to_value(
            commands::get_comfyui_client_task_statuses(
                argument(args, "serverUrl")?,
                argument(args, "clientIds")?,
                argument(args, "imageClientIds")?,
                argument(args, "videoOutputNodeIds")?,
            )
            .await?,
        )
        .map_err(|e| e.to_string()),
        "cancel_comfyui_workflow" => serde_json::to_value(
            commands::cancel_comfyui_workflow(
                argument(args, "serverUrl")?,
                argument(args, "clientId")?,
                State(&state.core),
            )
            .await?,
        )
        .map_err(|e| e.to_string()),
        "get_runtime_info" => serde_json::to_value(commands::get_runtime_info(State(&state.core)))
            .map_err(|e| e.to_string()),
        "submit_comfyui_video_upscale" => serde_json::to_value(
            video_upscale::submit_comfyui_video_upscale(
                argument(args, "input")?,
                State(&state.core),
                Channel::new(channel(state, args)),
            )
            .await?,
        )
        .map_err(|e| e.to_string()),
        "capture_video_poster" => serde_json::to_value(
            video_posters::capture_video_poster(argument(args, "source")?).await?,
        )
        .map_err(|e| e.to_string()),
        _ => Err(format!("Unknown command: {command}")),
    }
}
